@CD /D "%~dp0"
@SET OUTPUT_DIR=%CD%\Bin\Release
@SET DEPLOY_DIR=%LOCALAPPDATA%\ReportWatcher
@SET SOLUTION_FILE="%CD%\ReportWatcher.sln"
@set LOG_FILE=Release.log

@GOTO %PROCESSOR_ARCHITECTURE%

:AMD64
@SET PROGRAM_FILES=%ProgramFiles(x86)%
@GOTO SET_MSBUILD

:X86
@SET PROGRAM_FILES=%ProgramFiles%
@GOTO SET_MSBUILD

:SET_MSBUILD
@SET NET_FRAMEWORK="%PROGRAM_FILES%\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
@IF EXIST %NET_FRAMEWORK% @GOTO END

@SET NET_FRAMEWORK="%PROGRAM_FILES%\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe"
@IF EXIST %NET_FRAMEWORK% @GOTO END

@SET NET_FRAMEWORK="%PROGRAM_FILES%\MSBuild\14.0\Bin\MSBuild.exe"
@IF EXIST %NET_FRAMEWORK% @GOTO END

@ECHO Could not locate MSBuild. Process Halted!
@EXIT /B -1

:END
